# Linear Algebra

In [4]:
# Import Relevant Libraries
import numpy as np

In [40]:
# Define Variables
A = np.matrix([[1, 2, 3],[2, 7, 4]])
B = np.matrix([[1, -1],[0, -1]])
C = np.matrix([[5, -1],[9, 1],[6, 0]])
D = np.matrix([[3, -2, -1], [1, 2, 3]])

u = np.matrix([6, 2, -3, 5])
v = np.matrix([3, 5, -1 ,4])
w = np.matrix([1,8, 0, 5]).transpose()

## Part 1: Matrix Dimensions

In [41]:
# 1.1
print('Dimension of A:',np.shape(A))
# 1.2
print('Dimension of B:',np.shape(B))
# 1.3
print('Dimension of C:',np.shape(C))
# 1.4
print('Dimension of D:',np.shape(D))
# 1.5
print('Dimension of u:',np.shape(u))
# 1.6
print('Dimension of w:',np.shape(w))

Dimension of A: (2, 3)
Dimension of B: (2, 2)
Dimension of C: (3, 2)
Dimension of D: (2, 3)
Dimension of u: (1, 4)
Dimension of w: (4, 1)


# Part 2: Vector Operations

In [28]:
# Define Variables
alpha = 6

In [47]:
# 2.1 
print('u + v =', u + v)
# 2.2
print('u - v =', u - v)
# 2.3
print('alpha * u =', alpha * u)
# 2.4
print('u * v =', int(u * v.transpose()))
# 2.5
print('||u|| =', np.linalg.norm(u))

u + v = [[ 9  7 -4  9]]
u - v = [[ 3 -3 -2  1]]
alpha * u = [[ 36  12 -18  30]]
u * v = 51
||u|| = 8.60232526704


# Part 3: Matrix Operations

In [61]:
# 3.1
print('A + C = Not Defined')
# 3.2
print("A - C'=", A - C.transpose())
# 3.3
print("C' + 3D =", C.transpose() + 3*D)
# 3.4
print('BA =',B*A)
# 3.5
print("BA' = Not Defined")
# 3.6
print("BC = Not Defined")
# 3.7
print("CB =", C*B)
# 3.8
print("B^4 =",B^4)
# 3.9
print("AA' =",A*A.transpose())
# 3.10
print("D'D =",D.transpose()*D)

A + C = Not Defined
A - C'= [[-4 -7 -3]
 [ 3  6  4]]
C' + 3D = [[14  3  3]
 [ 2  7  9]]
BA = [[-1 -5 -1]
 [-2 -7 -4]]
BA' = Not Defined
BC = Not Defined
CB = [[  5  -4]
 [  9 -10]
 [  6  -6]]
B^4 = [[ 5 -5]
 [ 4 -5]]
AA' = [[14 28]
 [28 69]]
D'D = [[10 -4  0]
 [-4  8  8]
 [ 0  8 10]]
